[ENH]: Raise/warn if element is not ran
juaml/junifer pull request #319
Opened 2024-12-18 17:22 UTC by synchon

### Are you requiring a new dataset or marker?

- [X] I understand this is not a marker or dataset request

### Which feature do you want to include?

I just did this:

```
  patterns:
    VBM_GM: 
        pattern: derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
        space: MNI152NLin2009cAsym
  replacements: 
    - subject
```

and then tried to run junifer with `--element sub-0001`. 

The issue (which take me a lot of time to solve) is that `sub-0001` is not in the _elements_ list, since the replacement is without the `sub-` prefix.

Now, there was no issue/warning from the run function. It cloned the dataset, did nothing and dropped the dataset.

### How do you imagine this integrated in junifer?

We should implement a check in which if some of the elements in the list is not selected by the filter, there's a warning/error.

Exactly here is where we pass through the filter.

https://github.com/juaml/junifer/blob/a9e799caa3433d3d4eaa633d4565771b8eb297f6/junifer/api/functions.py#L170-L178

We should somehow keep a list of "unselected" elements so we can raise the warning.

### Do you have a sample code that implements this outside of junifer?

_No response_

### Anything else to say?

_No response_

2025-01-02 13:24 UTC, fraimondo commented on junifer/api/functions.py
> +            # Keep track of valid selectors
This logic won't work in case element is part of a tuple of elements.

The idea is that we can have subject/session/task/etc as the element but only pass the "subject" part an the filter function will return all of the elements for that subject.


I think that the logic should be to check if all items in the `element` array yielded at least one valid element.

2025-01-02 15:34 UTC, synchon commented on junifer/api/functions.py
> +            # Keep track of valid selectors
Let me try to make it concrete and maybe it'll be easier to understand:

For this DataGrabber:

```yaml
...
...
...
datagrabber:
  kind: DMCC13Benchmark
  types:
    - BOLD 
...
...
...
```

`junifer list-elements <yaml>` will give you:

```console
...
...
...
sub-f9057kp,ses-wave1pro,Rest,AP,1
sub-f9057kp,ses-wave1pro,Rest,PA,2
sub-f9057kp,ses-wave1rea,Rest,AP,1
sub-f9057kp,ses-wave1rea,Rest,PA,2
```

Now if I do:

```console
junifer run <yaml> --element sub-f9057kp
```
will run all "four" elements of the "subject".

Now, if I instead do:

```console
junifer run <yaml> --element sub-f9057k
```
it'd just "exit" without the changes in this PR, but give you this:
```console
...
...
...
RuntimeError: The following element selectors are invalid:
{'sub-f9057k'}
```
with the current PR. Also, doing this:

```console
junifer run <yaml> --element sub-f9057kp,ses-wave1pr
```
would give you:
```console
...
...
...
RuntimeError: The following element selectors are invalid:
{('sub-f9057kp', 'ses-wave1pr')}
```
Is this what you meant or something else?

2025-01-04 08:26 UTC, fraimondo commented on junifer/api/functions.py
> +            # Keep track of valid selectors
That's what I meant. I'm kind of rusty now, but I had the impression that the PR would not account for that logic.

2025-01-06 10:34 UTC, synchon commented on junifer/api/functions.py
> +            # Keep track of valid selectors
Resolving it then.

2025-01-07 21:50 UTC, fraimondo requested changes

2025-01-07 21:50 UTC, fraimondo commented on junifer/api/tests/test_functions.py
> +@pytest.mark.parametrize(
Can you add a test case for the case we discussed?

Ej, sub-01 exists, but ses-02 does not.

2025-01-08 15:18 UTC, fraimondo approved these changes

2025-01-08 15:18 UTC, fraimondo commented
Once CI is green, LGTM!

2025-01-08 17:29 UTC, merged