add grabber for local VBM AOMIC 1000 dataset
juaml/junifer pull request #57
Opened 2022-09-13 11:32 UTC by FeHoff

Add a new datagrabber for example dataset from OpenNeuro AOMIC 1000  
VBM is stored on Juseless

2022-09-13 12:37 UTC, fraimondo requested changes

2022-09-13 12:37 UTC, fraimondo commented on junifer/configs/juseless/juseless.py
> +class JuselessDataladAOMICVBM(PatternDataladDataGrabber):
Check the linter:

```
  junifer/configs/juseless/juseless.py:46:1: E302 expected 2 blank lines, found 1
  junifer/configs/juseless/juseless.py:63:80: E501 line too long (83 > 79 characters)
```

2022-10-04 13:51 UTC, verakye commented
@LeSasse The AOMIC1000 as indicated in issue #60 and the respective pull request in #76 was added to junifer. In the source code you can find the url to the respective dataset where you can see all the data included (https://github.com/juaml/junifer/blob/5ee2f05ccb450584e2d5b297b1f54c28a64eb390/junifer/datagrabber/aomic1000.py#L82). This doesn't include the PIOP1 and PIOP2 datasets.

2022-10-04 13:56 UTC, LeSasse commented
> @LeSasse The AOMIC1000 as indicated in issue #60 and the respective pull request in #76 was added to junifer. In the source code you can find the url to the respective dataset where you can see all the data included (
> 
> https://github.com/juaml/junifer/blob/5ee2f05ccb450584e2d5b297b1f54c28a64eb390/junifer/datagrabber/aomic1000.py#L82
> ). This doesn't include the PIOP1 and PIOP2 datasets.

Nice thank you! I will make an issue and implement PIOP1 and 2 based on your ID1000 datagrabber.

2022-10-06 13:27 UTC, synchon commented on junifer/configs/juseless/juseless.py
> +class JuselessDataladAOMICVBM(PatternDataladDataGrabber):
Should be fixed now.

2022-10-06 13:28 UTC, synchon commented
If @FeHoff is okay with the changes, we can merge it @fraimondo after your review.

2022-10-17 19:23 UTC, FeHoff commented
> If @FeHoff is okay with the changes, we can merge it @fraimondo after your review.

Looks good to me

2022-10-18 09:20 UTC, synchon commented
@fraimondo The changes were valid before #100 and they were mostly `flake8` fixes, so it needs to be adjusted now. Which comment are you referring to?

2022-10-18 09:27 UTC, fraimondo commented
<img width="856" alt="Screenshot 2022-10-18 at 11 27 30" src="https://user-images.githubusercontent.com/4493699/196392386-8ac6be1c-06a7-4bfd-ad38-2d91bd7413d5.png">

2022-10-18 09:30 UTC, synchon commented
I see now. It's still Pending, which I'm guessing is probably due to the review not being finished?

I'll take a look and if @FeHoff has already tested then that helps as well.

2022-10-18 09:34 UTC, fraimondo commented
Still needs to be refactored to match the current submodule structure.

2022-10-18 09:34 UTC, synchon commented
Yes will do that.

2022-10-18 12:30 UTC, synchon commented
@fraimondo The refactoring is done and tests are okay, but the juseless test needs to wait until @FeHoff helps us with a solution for the data source as he has recently applied for a change of group for the dataset.

2022-10-18 13:03 UTC, FeHoff commented
> @fraimondo The refactoring is done and tests are okay, but the juseless test needs to wait until @FeHoff helps us with a solution for the data source as he has recently applied for a change of group for the dataset.

I only need 26GB of space, where we all have access and I can put the RIA there. I rsync it to `/data/project/deleted_every_sunday/dataladstore/` for testing now

2022-10-18 13:14 UTC, synchon commented
> > @fraimondo The refactoring is done and tests are okay, but the juseless test needs to wait until @FeHoff helps us with a solution for the data source as he has recently applied for a change of group for the dataset.
> 
> I only need 26GB of space, where we all have access and I can put the RIA there. I rsync it to `/data/project/deleted_every_sunday/dataladstore/` for testing now

Thanks, I'll test it out using that.

2022-10-18 19:26 UTC, fraimondo commented
@FeHoff according to [this](https://juaml.github.io/junifer/main/builtin.html#data-grabbers), the AOMIC ID1000 dataset is open without registration. For this datagrabber to be added, it should be on a location accessible to every person with a juseless account.

2022-10-21 07:03 UTC, FeHoff commented
> @FeHoff according to [this](https://juaml.github.io/junifer/main/builtin.html#data-grabbers), the AOMIC ID1000 dataset is open without registration. For this datagrabber to be added, it should be on a location accessible to every person with a juseless account.

I pushed the AOMIC ID1000 CAT data to GIN here: git@gin.g-node.org:/felixh/ds003097_ReproVBM.git
@synchon is testing it now

2022-10-28 08:32 UTC, fraimondo approved these changes
LGTM

2022-10-28 08:58 UTC, merged

2022-10-28 08:59 UTC, synchon commented
@FeHoff Thanks for your help! :D