Add camcan datagrabber
juaml/junifer pull request #99
Opened 2022-10-06 13:53 UTC by LeSasse

* [ ] fix #(issue number)
* [x] description of feature/fix
* [x] tests added/passed
* [x] add an entry to the [latest changes](../docs/changes/latest.inc)

This implements the JuselessDataladCamCANVBM datagrabber class. However, the issue should not be closed I think, because there is another CamCAN dataset possibly for fMRI and other data types which will need another datagrabber I think.

2022-10-07 13:31 UTC, synchon requested changes

2022-10-07 13:31 UTC, synchon commented on docs/changes/latest.inc
> +- Implement a JuselessDataladCamCANVBM datagrabber class
Maybe add the link to the PR here.

2022-10-07 13:31 UTC, synchon commented on docs/builtin.rst
> +     - ``junifer.configs.juseless``
- ``junifer.configs.juseless.datagrabbers``

2022-10-07 13:31 UTC, synchon commented on docs/builtin.rst
> +   * - :class:`junifer.configs.juseless.JuselessDataladCamCANVBM`
`junifer.configs.juseless.datagrabbers.JuselessDataladCamCANVBM`

2022-10-10 07:25 UTC, synchon submitted a review, later dismissed

2022-10-10 12:06 UTC, fraimondo approved these changes

2022-10-10 12:06 UTC, fraimondo approved these changes

2022-10-10 12:30 UTC, merged